package com.creativedrewy.nativ.chainsupport.nft

sealed class NftMetaStatus

object Pending : NftMetaStatus()
object Invalid : NftMetaStatus()

class MetaLoaded(
    val metadata: NftMetadata
) : NftMetaStatus()

/**
 * Intermediary format to be generated by any compatible chain support module. Will be passed up
 * to consuming UI.
 */
data class NftMetadata(
    val name: String = "",
    val symbol: String = "",
    val description: String = "",
    val image: String = "",
    val animationUrl: String = "",
    val externalUrl: String = "",
    val attributes: List<NftAttributes> = listOf(),
    val properties: NftProperties = NftProperties()
)

data class NftAttributes(
    val traitType: String = "",
    val value: String = "",
    val traitCount: Int = 0
)

object NftCategories {
    const val VR = "vr"
    const val Model = "model"
    const val Image = "image"
}

data class NftProperties(
    val category: String = "",
    val files: List<FileDetails> = listOf()
)

object NftFileTypes {
    const val GLB = "glb"
    const val GLB_Binary = "gltf/binary"
}

data class FileDetails(
    val uri: String = "",
    val type: String = ""
)

data class NftCreator(
    val address: String = "",
    val verified: Boolean = false,
    val share: Int = 0
)
